### ISSUE TITLE
configurations of a fresh installation of BPG 

### ISSUE THREAD

**Issue by yaohuic** [BerkeleyPhotonicsGenerator/BPG#165]
Roughly go through a fresh installation of bpg and bag_framework as well. 

Not really successful at the end. Certain configuration files may not be up-to-date or in place/folder.

For example, when I try to execute: 

bpg setup_workspace

Following message popped up:
"
Loaded BPG v0.8.5
Environment variable BAG_WORK_DIR not set.
Description:Root directory where all generator folders are located
Environment variable BAG_CONFIG_PATH not set.
Description:Path to yaml file containing configuration for BAG and BPG
Environment variable BAG_FRAMEWORK not set.
Description:Path to BAG installation
Environment variable BAG_TEMP_DIR not set.
Description:Path to where temporary files will be placed
Environment variable BAG_TECH_CONFIG_DIR not set.
Description:Path to directory containing tech-specific configuration
Configuration yaml file not provided!

**Comment by pvnbhargava** [comment]
The very first call to setup_workspace is expected to be like this, we have not cleaned up all of our warning messages yet. After calling bpg setup_workspace, did you see an example_tech folder and a sourceme.sh file? If so then it was successful!

 Follow the rest of the instructions, which call for you to run source sourceme.sh, which will set up all these environment variables and configuration yaml files so that this warning won’t pop up next time

**Comment by pvnbhargava** [comment]
Also what procedure did you use to install BPG? Currently my installation instructions are incorrect, since bpg is not uploaded to PyPI yet

**Comment by yaohuic** [comment]
Thanks.   
In root/folder of BPG I download, I used:
python3 setup.py install

I also tried similar command (python3 setup.py install) to install BAG_framework, although I am not sure it is properly correlated with BPG installation.

With the project folder I created:
BAG_WORK_DIR=/home/demo

1. Somehow, after using "source sourceme.sh",  information points to a bag_config.yaml file did not exist in example_tech folder
BAG_CONFIG_PATH=/home/demo/example_tech/bag_config.yaml
2. Furthermore, there is no actual BAG_Framework folder as below 
BAG_FRAMEWORK=/home/demo/BAG_Framework



also

**Comment by pvnbhargava** [comment]
Can you elaborate a bit more on what you mean by it stopped you from moving further? We are still working on making a tutorial and more examples to demonstrate how to use BPG once this is set up. However, you should still be able to run the test suite as shown in: https://bpg.readthedocs.io/en/latest/getting_started/installation.html

You are correct that BAG_CONFIG_PATH is pointing to the wrong location. I will fix this tonight. The BAG_FRAMEWORK environment variable is no longer needed, and I can remove that tonight as well.

The base BAG_Framework installation process that you used should work. But in the future we will integrate BAG installation together with BPG so that it is easier.

**Comment by yaohuic** [comment]
Thanks.  
After I type in " bpg setup_test", the terminal crashed.....  The bpg_test_suite folder was not copied. 

I will do a clean re-install again in a clean ubuntu 18.04 VM, To see if anything improved.

**Comment by yaohuic** [comment]
Roughly I figure out the bug:

In my system, 
1. When I used:
bpg workspace_setup
will use /example_tech files from /anaconda3/lib/python3.7/site-packages/BerkeleyPhotonicsGenerator-0.8.5-py3.7.egg/BPG/examples/tech, 
where all .yaml configuration files are not there. 
Following is all the files show up in example_tech folder
![image](https://user-images.githubusercontent.com/47613391/65362881-68a57100-dc09-11e9-9d68-803d4e219c3b.png)

2. when I used:
bpg test_setup
no bpg_test_suite will be copied as /tests folder are not inside /anaconda3/lib/python3.7/site-packages/BerkeleyPhotonicsGenerator-0.8.5-py3.7.egg/BPG

Eventually, I manually copy-paste the missing files/folder from github into relevant workspace_folder.
It roughly makes pytest bpg_test_suite running now. 
![image](https://user-images.githubusercontent.com/47613391/65363159-c25a6b00-dc0a-11e9-8e9a-e4d015813465.png)

**Comment by pvnbhargava** [comment]
Thanks for the feedback. In general it sounds like the main problem is that the `bpg` command line options have some issues with properly setting up the space, particularly because of the install location. I will probably revert to providing a separate example repository with all of these files set up.

**Comment by pvnbhargava** [comment]
Ok I've finally had a chance to revisit this problem, and have pushed the fix to master. Thanks for your help!
